CC = gcc
CFLAGS = -Wall -Werror
LIBS = -lm

SRC = alarm-priority.c tests.c init.c malloc.c synch.c thread.c timer.c
OBJ = $(SRC:.c=.o)
EXEC = alarm-priority

all: $(EXEC)

$(EXEC): $(OBJ)
	$(CC) $(CFLAGS) $(LIBS) $(OBJ) -o $(EXEC)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ) $(EXEC)
